version: "3.9"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sispar
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  flask_app:
    build: .
    container_name: Teste_api
    depends_on:
      - mysql_db
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: /bin/sh -c "sleep 15 && flask run --host=0.0.0.0"

volumes:
  db_data:
